### ISSUE TITLE
Enhance namespace context to allow easy namespace context switching

### ISSUE THREAD

**Issue by showeimer** [kui-shell/plugin-kubeui#274]
Current behavior of clicking the current namespace context at the bottom just runs a `kubectl get namespaces` command; this result doesn't have a feature that allows the user to easily change the namespace context.

**Comment by hanqiuzh** [comment]
it will be nice to run `kubectl config set-context --current --namespace=SELECTED_NAMESPACE`  when user click a namespace

**Comment by starpit** [comment]
i thought that the table clicks (in the table that is presented after clicking on the namespace part at the bottom) does switch context? at least it does for plain kubernetes. is it different for your kube environment?

**Comment by hanqiuzh** [comment]
@starpit `contexts` switch works, but clicking `namespaces` just shows a sidecar:
<img width="861" alt="Screen Shot 2020-01-31 at 12 11 27 PM" src="https://user-images.githubusercontent.com/31426239/73559373-e59bef00-4422-11ea-8c58-9f8285a177b8.png">

**Comment by starpit** [comment]
got it, thanks for the clarification. yes indeed, this would be a nice feature. on the surface, we couldn't do this trivially, since kubectl context management has no concept of "just switching namespaces". we would need to invent something here. e.g. ... do we create a new context for every namespace switch? do we then present these as "contexts" in the context list?

so i think there are some design issues that need to be worked through. but it'd a nice feature to have.

**Comment by starpit** [comment]
along somewhat similar lines: the kui tab state could be extended to include kube context, or kube namespace. if we extend the kui tab state to e.g. kube namespace, we could use this as an "above board" way to solve the namespace selection problem

that is, kui would manage namespace selection, without having to force this through to the kube context level.

it would also mean that, as i switch tabs, i switch namespaces (i.e. as a user i can associate kube namespaces to tabs). we could then look into color-coding the bottom stripe by namespace, etc.

**Comment by starpit** [comment]
we could allow status stripe contributions to participate in tab state automatically, i.e. extend the status stripe contribution api to allow contributors to specify that this choice should be attached to tabs, and let kui core take care of managing the rest

**Comment by hanqiuzh** [comment]
see https://github.com/kui-shell/plugin-kubeui/issues/274#issuecomment-580821280
I think this command can just switch namespace of current context:

```
kubectl config set-context --current --namespace=SELECTED_NAMESPACE
```

And as a desktop user, I think I'm OK with all tabs share the same context & namespace.

**Comment by starpit** [comment]
Great! Then this could be a small fix!

**Comment by showeimer** [comment]
@starpit I agree with @hanqiuzh.  I think it's better when starting with new features to start small, just adding the simple on click handler to run the command above is the best place to start.  

Your ideas do sound interesting, particularly in an MCM context, so they would be worth revisiting and flushing out.   I'm not sure it makes sense to extend the tab state with repeated information, when the context is already and always present at the bottom.  For now, we just want some parity in how the current cluster context button works, where it's presenting a table with different cluster contexts and click functionality that allows switching between them.

**Comment by starpit** [comment]
https://github.com/kui-shell/plugin-kubeui/pull/310 will introduce a config.d file `kubectl.json` with this setting:

  "summarizeNamespaceOnSwitch": true

if false, then namespace switching will return immediately with "ok"; otherwise, namespace switching will respond with a summary of the resources in that namespace. this might be too high latency for production clusters, so i have made it optional.

**Comment by starpit** [comment]
there are a few bugs in the impl offered by #310: the radio table is only presented for command line "k get ns" not the status widget click handler; row clicks in that table should do a plain `k get ns -o yaml`
