### ISSUE TITLE
optimize context and namespace widgets: is it possible only to update when context actually changes?

### ISSUE THREAD

**Issue by showeimer** [kui-shell/plugin-kubeui#278]
While investigating some issues with the namespace context feature; I noticed that any and all commands that I execute will also execute `kubectl config current-context`; for example I run `ls` and that command also gets run.  So for every command the user enters; it's two commands that are run which is not ideal in a shared pod situation.

**Comment by starpit** [comment]
agreed. especially since the context and namespace widget both feed off the same data. right now, these are implemented as completely distinct widgets. we could probably find a way so that these two widgets to share the data fetched by one of them

**Comment by starpit** [comment]
#326 will halve the load caused by the widgets. any further optimization will require more careful thought. ideally, we would only update the widgets when the context actually changes. how do we know this? in an enclosed kui world (where only kui commands can change the context), perhaps we could encode this knowledge into those commands -- i.e. they can fire the onchange events...

in an electron environment, where the context might change outside of the kui, that approach could lead to stale status widgets. also, nothing is to stop the user manually editing the underlying json/yaml files, or using some escape hatch that sidesteps the kui commands -- e.g. `bash -c "kubectl config set-context"`.

hooking into the filewatch api provided by the host OS might be a way to solve this definitively, but... that's a big undertaking.
so, for now, i propose we be
